import { Theme, Icons } from "../../theme.slint";
import { Store, TabIndex, RssConfig } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Btn, IconBtn, NoMessageImg, Label } from "../../base/widgets.slint";
import { CheckBox, ComboBox, LineEdit } from "std-widgets.slint";

enum BtnIndex {
    New,
    Edit,
    Delete,
}

component Head inherits Rectangle {
    height: Theme.header-height;

    HorizontalLayout {
        alignment: start;
        padding-left: Theme.padding;
        padding-right: Theme.padding;

        IconBtn {
            icon-width: Theme.icon-size * 0.7;
            background: Colors.transparent;
            icon: Icons.add-fill;
            text: Logic.tr(Store.is-cn, "添加");
        }
    }
}

component RssList inherits Rectangle {
    private property<length> item-height: 40px;
    private property<color> selected-item-color: Theme.dark-fill-color;
    out property<string> current-uuid;

    if Store.rss-lists.length == 0 : Rectangle {
        NoMessageImg {
            width: parent.width * 0.6;
            text: Logic.tr(Store.is-cn, "没有订阅");
        }
    }

    Flickable {
        viewport-height: Store.rss-lists.length * root.item-height;

        for data[index] in Store.rss-lists : Rectangle {
            y: index * item-height;
            height: root.item-height;

            background: data.uuid == root.current-uuid ? root.selected-item-color : Colors.transparent;

            touch := TouchArea {
                clicked => { root.current-uuid = data.uuid; }
            }

            HorizontalLayout {
                padding-left: Theme.padding * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 2;

                    VerticalLayout {
                        alignment: center;
                        IconBtn {
                            icon: Store.icons-dialog-setting.icons[Math.max(0, Math.min(data.icon-index, Store.icons-dialog-setting.icons.length - 1))];
                            width: Theme.icon-size * 1.2;
                            background: Colors.transparent;
                        }
                    }

                    Label {
                        text: data.name;
                        overflow: elide;
                    }
                }

                HorizontalLayout {
                    alignment: end;
                    spacing: Theme.spacing * 2;
                    padding-right: Theme.padding;

                    VerticalLayout {
                        alignment: center;
                        IconBtn {
                            icon: Icons.star;
                            colorize: data.is-mark ? Theme.mark-color : Theme.unmark-color;
                            clicked => { Logic.toggle-rss-mark(index, data.uuid); }
                        }
                    }
                }
            }
        }
    }
}

component RssListBtns inherits HorizontalLayout {
    in property<string> current-uuid;
    private property <length> btn-width: 100px;

    alignment: center;
    spacing: Theme.spacing * 4;
    padding: Theme.padding * 4;

    callback current-btn-index(BtnIndex);

    IconBtn {
        width: root.btn-width; height: 40px;
        text: Logic.tr(Store.is-cn, "新建");
        icon: Icons.add-fill;
        icon-width: Theme.icon-size * 0.8;
        border-radius: self.height / 2;
        bg-color: Theme.success-color.darker(10%);
        bg-pressed-color: self.bg-color.darker(30%);
        colorize: Theme.basic-white-color;

        clicked => { current-btn-index(BtnIndex.New); }
    }

    IconBtn {
        width: root.btn-width;
        text: Logic.tr(Store.is-cn, "编辑");
        icon: Icons.edit;
        border-radius: self.height / 2;
        bg-color: Theme.info-color.brighter(20%);
        bg-pressed-color: self.bg-color.darker(30%);
        colorize: self.bg-pressed-color.darker(50%);

        clicked => { current-btn-index(BtnIndex.Edit); }
    }

    IconBtn {
        width: root.btn-width;
        text: Logic.tr(Store.is-cn, "删除");
        icon: Icons.delete;
        border-radius: self.height / 2;
        bg-color: Theme.danger-color;
        bg-pressed-color: self.bg-color.darker(30%);
        colorize: self.bg-pressed-color.darker(50%);

        clicked => {
            current-btn-index(BtnIndex.Delete);
            Logic.delete-rss(root.current-uuid);
        }
    }
}

component AddEdit inherits Rectangle {
    property<length> text-width: Theme.default-label-width;
    in-out property<int> icon-index: 0;

    public function get() -> RssConfig {
        return {
            name: line-edit-name.text,
            url: line-edit-url.text,
            use-proxy: use-proxy-checkbox.checked,
            is-favorite: favorite-checkbox.checked,
            icon-index: root.icon-index,
            feed-format: feed-format-combobox.current-value,
        };
    }

    public function set(config: RssConfig) {
        line-edit-name.text = config.name;
        line-edit-url.text = config.url;
        use-proxy-checkbox.checked = config.use-proxy;
        favorite-checkbox.checked = config.is-favorite;
        root.icon-index = config.icon-index;

        feed-format-combobox.current-value = config.feed-format;
        if (config.feed-format == "") {
            feed-format-combobox.current-value = feed-format-combobox.model[0];
        }
    }

    VerticalLayout {
        alignment: start;
        padding: Theme.padding * 2;
        spacing: Theme.spacing * 4;

        VerticalLayout {
            alignment: start;
            spacing: Theme.spacing;

            txt-name := Label {
                font-size: Theme.title4-font-size;
                width: root.text-width;
                text: Logic.tr(Store.is-cn, "Rss名称和图标");
            }

            HorizontalLayout {
                height: txt-name.preferred-height * 1.33;
                spacing: Theme.spacing;

                line-edit-name := LineEdit {
                    placeholder-text: Logic.tr(Store.is-cn, "请输入Rss名称");
                }

                rss-icon := IconBtn {
                    width: self.height;
                    icon: Store.icons-dialog-setting.icons[Math.max(0, Math.min(root.icon-index, Store.icons-dialog-setting.icons.length - 1))];
                    clicked => { Store.icons-dialog-setting.show = true; }
                }
            }
        }

        VerticalLayout {
            alignment: start;
            spacing: Theme.spacing;

            txt-url := Label {
                font-size: Theme.title4-font-size;
                width: root.text-width;
                text: Logic.tr(Store.is-cn, "Rss源地址");
            }

            line-edit-url := LineEdit {
                height: txt-url.preferred-height * 1.33;
                placeholder-text: Logic.tr(Store.is-cn, "请输入Rss源地址");
            }
        }

        VerticalLayout {
            alignment: start;
            spacing: Theme.spacing;

            txt-feed-format := Label {
                text: Logic.tr(Store.is-cn, "Rss源格式");
            }

            feed-format-combobox := ComboBox {
                height: txt-feed-format.preferred-height * 1.33;
                model: ["AUTO", "RSS", "ATOM"];
                current-value: self.model[0];
            }
        }

        HorizontalLayout {
            spacing: Theme.spacing * 2;

            HorizontalLayout {
                width: 50%;
                use-proxy-checkbox := CheckBox {
                    text: self.checked ? Logic.tr(Store.is-cn, "已经启用代理") : Logic.tr(Store.is-cn, "未启用代理");
                }
            }

            HorizontalLayout {
                favorite-checkbox := CheckBox {
                    text: self.checked ? Logic.tr(Store.is-cn, "已经关注") : Logic.tr(Store.is-cn, "未关注");
                }
            }
        }
    }
}


component AddEditBtns inherits HorizontalLayout {
    private property <length> btn-width: 100px;

    alignment: center;
    spacing: Theme.spacing * 10;
    padding: Theme.padding * 4;

    callback cancel-clicked();
    callback ok-clicked();

    IconBtn {
        width: root.btn-width; height: 40px;
        text: Logic.tr(Store.is-cn, "取消");
        icon: Icons.delete;
        icon-width: Theme.icon-size;
        border-radius: self.height / 2;
        bg-color: Theme.info-color.brighter(20%);
        bg-pressed-color: self.bg-color.darker(30%);
        colorize: self.bg-pressed-color.darker(50%);

        clicked => { root.cancel-clicked(); }
    }

    IconBtn {
        width: root.btn-width;
        text: Logic.tr(Store.is-cn, "确定");
        icon: Icons.success-fill;
        border-radius: self.height / 2;
        bg-color: Theme.success-color.darker(20%);
        bg-pressed-color: self.bg-color.darker(30%);
        colorize: Theme.basic-white-color;

        clicked => { root.ok-clicked(); }
    }
}


component Body inherits Rectangle {
    private property <BtnIndex> rss-list-btns-index;
    in-out property icon-index <=> ae.icon-index;

    rsslist-vbox := VerticalLayout {
        rsslist := RssList { }

        RssListBtns {
            current-uuid: rsslist.current-uuid;

            current-btn-index(index) => {
                root.rss-list-btns-index = index;

                if (index == BtnIndex.New) {
                    rsslist-vbox.visible = false;
                    ae.set({});
                } else if (index == BtnIndex.Edit) {
                    rsslist-vbox.visible = false;
                    ae.set(Logic.get-rss-ae-setting(rsslist.current-uuid));
                } else if (index == BtnIndex.Delete) {
                    Logic.delete-rss(rsslist.current-uuid);
                }
            }
        }
    }

    ae-vbox := VerticalLayout {
        visible: !rsslist-vbox.visible;
        spacing: Theme.spacing * 4;
        alignment: start;

        ae := AddEdit {}

        AddEditBtns {
            cancel-clicked => {
                rsslist-vbox.visible = true;
            }

            ok-clicked => {
                rsslist-vbox.visible = true;

                if (root.rss-list-btns-index == BtnIndex.New) {
                    Logic.new-rss(ae.get());
                } else if (root.rss-list-btns-index == BtnIndex.Edit) {
                    Logic.save-rss(rsslist.current-uuid, ae.get());
                }
            }
        }
    }
}

export component Add inherits VerticalLayout {
    visible: TabIndex.Add == Store.current-tab-index;
    spacing: Theme.spacing;

    in-out property icon-index <=> body.icon-index;

    head := Head {}
    body := Body {}
}
