import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { Rss } from "./rss.slint";
import { Add } from "./add.slint";
import { Favorite } from "./favorite.slint";
import { Setting } from "./setting.slint";

export component Bodyer inherits Rectangle {
    Rss {}
    Add {}
    Favorite {}
    Setting {}
}

