import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { Rss } from "./rss.slint";
import { Add } from "./add.slint";
import { Favorite } from "./favorite.slint";
import { Setting } from "./setting.slint";
import { Find } from "./find.slint";

export component Bodyer inherits Rectangle {
    in-out property icon-index <=> add.icon-index;

    Rss {}
    Favorite {}
    add := Add {}
    Find {}
    Setting {}
}

