import { Theme, Icons } from "../../theme.slint";
import { Store, TabIndex } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn, Label } from "../../base/widget.slint";

component Head inherits Rectangle {
    height: Theme.header-height;

    IconBtn {
        x: Theme.padding;
        background: Colors.transparent;
        icon: Icons.setting-fill;
        text: Logic.tr(Store.is-cn, "设置");
    }
}

component Body inherits Rectangle {
    background: green;
}

export component Setting inherits VerticalLayout {
    visible: TabIndex.Setting == Store.current-tab-index;
    spacing: Theme.spacing;

    head := Head {}
    body := Body {}
}

