import { Theme } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store } from "../store.slint";
import { Bodyer } from "./bodyer/panel.slint";
import { Footer } from "./footer.slint";

export component Panel inherits VerticalLayout {
    padding: Theme.padding;
    padding-top: 0;
    padding-bottom: 0;

    bodyer := Bodyer {
        height: parent.height - footer.height - parent.padding;
    }

    footer := Footer { }
}
