import { Theme } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store, SettingDetailIndex } from "../store.slint";
import { Bodyer } from "./bodyer/panel.slint";
import { Footer } from "./footer.slint";

export component Panel inherits VerticalLayout {
    padding: Theme.padding;
    padding-top: 0;
    padding-bottom: 0;

    property <bool> isShowFooter: Store.current-setting-detail-index == SettingDetailIndex.Home;

    Bodyer {
        height: parent.height - (isShowFooter ? (Theme.footer-height + Theme.padding) : 0);
    }

    if isShowFooter:  Footer { }
}
