import { Theme, Icons } from "../theme.slint";
import { IconBtn } from "./icon-btn.slint";

export component CancelBtn inherits IconBtn {
    use-auto-size: true;
    icon: Icons.cancel;
    icon-width: Theme.icon-size;
    border-radius: self.height / 2;
    bg-color: Theme.info-color.brighter(50%);
    bg-pressed-color: self.bg-color.darker(30%);
    colorize: self.bg-pressed-color.darker(100%);
}

export component ConfirmBtn inherits IconBtn {
    use-auto-size: true;
    icon: Icons.success-fill;
    border-radius: self.height / 2;
    bg-color: Theme.success-color.darker(20%);
    bg-pressed-color: self.bg-color.darker(30%);
    colorize: Theme.basic-white-color;
}
