import { Theme, Icons } from "../theme.slint";
import { IconBtn } from "./icon-btn.slint";

export component Head inherits Rectangle {
    height: Theme.header-height;

    in-out property<string> title;
    in-out property icon <=> ic.icon;
    in-out property icon-width <=> ic.icon-width;
    in-out property<LayoutAlignment> hbox-alignment: LayoutAlignment.stretch;

    callback clicked <=> ic.clicked;

    hbox := HorizontalLayout {
        alignment: hbox-alignment;
        padding-left: Theme.padding;
        padding-right: Theme.padding;

        ic := IconBtn {
            icon-width: Theme.icon-size;
            background: Colors.transparent;
            icon: Icons.back;
            text: root.title;
        }

        @children
    }

}
