import { Theme } from "../theme.slint";
import { Label } from "./label.slint";

export component IconBtn inherits Rectangle {
    in-out property icon <=> img.source;
    in-out property colorize <=> img.colorize;
    in-out property icon-width <=> img.width;
    in-out property icon-rotation-angle <=> img.rotation-angle;
    in-out property text <=> txt.text;

    callback clicked <=> touch.clicked;

    in-out property<color> bg-color: transparent;
    in-out property<color> bg-pressed-color: Theme.pressed-color;

    width: hbox.preferred-width + Theme.padding;
    background: touch.pressed ? bg-pressed-color : bg-color;

    animate background {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    hbox := HorizontalLayout {
        spacing: txt.visible ? Theme.spacing * 2 : 0px;

        img := Image {
            width: Theme.icon-size;
            colorize: Theme.icon-color;
        }

        txt := Label {
            visible: text != "";
            width: self.visible ? self.preferred-width : 0px;
            color: img.colorize;
        }
    }

    touch := TouchArea { }
}
