import { Theme } from "../theme.slint";
import { Label } from "./label.slint";

export component IconBtn inherits Rectangle {
    in-out property icon <=> img.source;
    in-out property colorize <=> img.colorize;
    in-out property icon-width <=> img.width;
    in-out property icon-rotation-angle <=> img.rotation-angle;
    in-out property<bool> is-ltr: true;

    in-out property<string> text;
    in-out property<length> font-size: Theme.title4-font-size;

    callback clicked <=> touch.clicked;

    in-out property<color> bg-color: transparent;
    in-out property<color> bg-pressed-color: Theme.pressed-color;

    border-radius: Theme.border-radius;
    background: touch.pressed ? bg-pressed-color : bg-color;

    animate background {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    hbox := HorizontalLayout {
        spacing: Theme.spacing * 2;
        alignment: center;

        if !root.is-ltr && root.text != "" : Label {
            color: img.colorize;
            font-size: root.font-size;
            text: root.text;
        }

        img := Image {
            width: Theme.icon-size;
            colorize: Theme.icon-color;
        }

        if root.is-ltr && root.text != "" : Label {
            color: img.colorize;
            font-size: root.font-size;
            text: root.text;
        }
    }

    touch := TouchArea { }
}
