import { Dialog } from "./dialog.slint";
import { Store } from "../store.slint";
import { Util } from "../util.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "../theme.slint";
import { Label } from "./label.slint";
import { CancelBtn, TextBtn } from "./btn.slint";

export global OkCancelDialogSetting {
    in-out property <string> title-type: "warning";
    in-out property <string> title-text: "警告";
    in-out property <string> body-text;
    in-out property <string> handle-type;
    in-out property <string> handle-uuid;
}

export component OkCancelDialog inherits Dialog {
    title: OkCancelDialogSetting.title-text;
    title-bg: Util.text-color(OkCancelDialogSetting.title-type);
    preferred-width: 200px;
    height: 200px;
    background: rect.background;

    rect := Rectangle {
        background: Theme.base-background-light;
        Label {
            width: 100%;
            horizontal-alignment: center;
            text: OkCancelDialogSetting.body-text;
            wrap: word-wrap;
            font-size: Theme.title4-font-size;
        }
    }

    ok-clicked => {
        Logic.handle-ok-cancel-dialog(OkCancelDialogSetting.handle-type, OkCancelDialogSetting.handle-uuid);
        OkCancelDialogSetting.body-text = "";
    }

    cancel-clicked => {
        OkCancelDialogSetting.body-text = "";
    }
}

export component OkCancelDialogV2 inherits Rectangle {
    preferred-width: 200px;
    height: vbox.preferred-height;
    background: Theme.base-background-light;

    in-out property <bool> is-prevent-event-forward: false;
    in-out property <string> title: OkCancelDialogSetting.title-text;

    if is-prevent-event-forward: TouchArea { }

    vbox := VerticalLayout {
        alignment: start;
        padding: Theme.padding * 4;
        spacing: Theme.spacing * 4;

        title-label := Label {
            text: root.title;
            color: Theme.primary-text-color;
            font-size: Theme.title1-font-size;
        }

        Label {
            wrap: word-wrap;
            color: Theme.secondary-text-color;
            font-size: Theme.title4-font-size;
            text: OkCancelDialogSetting.body-text;
        }

        HorizontalLayout {
            alignment: end;
            spacing: Theme.spacing * 4;

            TextBtn {
                icon: Icons.success;
                text: Logic.tr(Store.is-cn, "确认");

                clicked => {
                    Logic.handle-ok-cancel-dialog(OkCancelDialogSetting.handle-type, OkCancelDialogSetting.handle-uuid);
                    OkCancelDialogSetting.body-text = "";
                }
            }

            TextBtn {
                text: Logic.tr(Store.is-cn, "取消");
                icon: Icons.cancel;

                clicked => {
                    OkCancelDialogSetting.body-text = "";
                }
            }
        }
    }
}
