import { Theme } from "../theme.slint";

export component TabBtn inherits Rectangle {
    in-out property icon <=> img.source;
    in-out property icon-width <=> img.width;
    in-out property icon-rotation-angle <=> img.rotation-angle;
    in-out property text <=> txt.text;

    in-out property<length> icon-size: Theme.icon-size;
    in-out property<color> colorize: Theme.icon-color;
    in-out property<bool> checked: false;

    callback clicked();

    in-out property<color> bg-color: Colors.transparent;
    in-out property<color> bg-pressed-color: Colors.transparent;

    background: touch.pressed ? bg-pressed-color : bg-color;

    animate background {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    VerticalLayout {
        padding: 1px;
        HorizontalLayout {
            alignment: center;
            img := Image {
                width: root.icon-size;
                colorize: root.checked ? Theme.brand-color : root.colorize;
            }
        }

        HorizontalLayout {
            alignment: center;
            txt :=  Text {
                font-size: img.width * 0.4;
                color: img.colorize;
            }
        }
    }

    fs := FocusScope {}

    touch := TouchArea {
        mouse-cursor: MouseCursor.pointer;
        clicked => {
            fs.focus();
            root.clicked();
        }
    }
}
