import { TextEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component TxtEdit inherits Rectangle {
    clip: true;
    forward-focus: edit;
    border-width: 1px;
    border-radius: Theme.border-radius;
    border-color: edit.has-focus ? Theme.brand-color : Theme.placeholder-text-color;

    in-out property text <=> edit.text;
    callback edited <=> edit.edited;

    public function clear() {
        root.text = "";
    }

    hbox := HorizontalLayout {
        padding: Theme.padding * 2;
        padding-right: 0;

        edit := TextEdit {
            font-size: Theme.default-font-size;
        }

        // Flickable {
        //     viewport-height: edit.preferred-height;

            // edit := TextInput {
                // font-size: Theme.default-font-size;
                // single-line: false;
                // wrap: word-wrap;
            // }
        // }
    }
}
