import { Theme } from "./theme.slint";
import { Logic } from "./logic.slint";
import { Store } from "./store.slint";
import { Util } from "./util.slint";
import { Panel } from "./panel/panel.slint";
import { Message } from "./base/message.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    width: Theme.default-width;
    // height: Theme.default-height;
    background: Theme.basic-black-color;
    icon: @image-url("./images/icon.png");
    title: "rssbox";

    init => { }

    Rectangle {
        background: Theme.base-background;
        panel := Panel { }
    }

    modal := Rectangle {
        function hide() { }
    }

    msg := Message {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        text: Store.message.text;
        type: Store.message.text-type;
        clicked => {
            Logic.copy-to-clipboard(self.text);
        }
    }
}

export { Util, Logic, Store }
