import { Theme, Icons } from "./theme.slint";
import { Logic } from "./logic.slint";
import { Store } from "./store.slint";
import { Util } from "./util.slint";
import { Panel } from "./panel/panel.slint";
import { Toast, IconsDialog, IconsDialogSetting, OkCancelDialogV2, Blanket, LanguageDialog, InputBar, OkCancelDialogSetting } from "./base/widgets.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;

    background: Theme.base-background-light;
    icon: Icons.brand;
    title: "rssbox";

    Panel { }

    if IconsDialogSetting.show || OkCancelDialogSetting.body-text != "" || Store.is-first-run: Blanket { }

    if IconsDialogSetting.show: IconsDialog {
        select-index(index) => {
            Store.icon-index = index;
        }
    }

    if OkCancelDialogSetting.body-text != "": OkCancelDialogV2 {
        width: Math.min(root.width * 0.9, 380px);
    }

    if Store.is-first-run: LanguageDialog {
        is-hide-close-btns: true;
        width: Math.min(300px, root.width * 0.8);
    }

    if Store.message.text != "": Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        inner-max-width: root.width * 80%;
        text: Store.message.text;
        type: Store.message.text-type;
        clicked => {
            Logic.copy-to-clipboard(self.text);
        }
    }
}

export { Util, Logic, Store }
