import { RssConfig, RssEntry, SettingUI, SettingSync, SettingProxy } from "./store.slint";

export global Logic {
    callback new-rss(RssConfig);
    callback update-rss(string, RssConfig);
    callback remove-rss(string); // suuid
    callback switch-rss(string, string); // from_suuid, to_suuid
    callback toggle-rss-favorite(string); // suuid
    callback sync-rss(string); // suuid
    callback sync-rss_all();
    callback get-rss-config-to-ui(string) -> RssConfig; // suuid
    callback exist-rss(string) -> bool; // suuid

    pure callback update-time-rss(string, bool) -> string; // suuid, toggle_flag
    update-time-rss => { return "10-33 12:09:45"; }

    callback remove-entry(string, string); // suuid, uuid
    callback remove-all-entrys(string); // suuid
    callback remove-favorite-entry(string); // uuid
    callback remove-all-favorite-entrys();
    callback favorite-entry(string, string); // suuid, uuid
    callback set-entry-read(string, string); // suuid, uuid

    callback remove-all-cache();

    callback copy-to-clipboard(string); // msg
    callback copy-from-clipboard() -> string;
    callback show-message(string, string);
    callback handle-ok-cancel-dialog(string, string);

    callback get-setting-ui() -> SettingUI;
    callback set-setting-ui(SettingUI);

    callback get-setting-sync() -> SettingSync;
    callback set-setting-sync(SettingSync);

    callback get-setting-proxy() -> SettingProxy;
    callback set-setting-proxy(SettingProxy);

    pure callback tr(bool, string) -> string;
    tr(is-cn, text) => { return text; }
}

