import { RssConfig, RssEntry, SettingDialogConfig } from "./store.slint";

export global Logic {
    callback new-rss(RssConfig);
    callback save-rss(string, RssConfig);
    callback delete-rss(string);
    callback switch-rss(string, string);
    callback toggle-rss-mark(int, string);

    pure callback update-time-rss(string) -> string; // suuid
    update-time-rss => { return "10-33 12:09:45"; }

    callback sync-rss(string); // suuid
    callback favorite-entry(string, string); // suuid, uuid
    callback remove-entry(string, string); // suuid, uuid
    callback remove-all-entrys(string); // suuid
    callback remove-favorite-entry(string); // uuid
    callback remove-all-favorite-entrys();
    callback set-read-entry(string, string); // suuid, uuid
    callback open-url(string);

    callback clean-cache();
    callback copy-to-clipboard(string);
    callback show-message(string, string);
    callback handle-ok-cancel-dialog(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    pure callback tr(bool, string) -> string;
    tr(is-cn, text) => {
        return text;
    }

    pure callback unread-counts([RssEntry], int, bool) -> int;
    unread-counts(entrys, counts, flag) => { return entrys.length; }

    pure callback get-update-time(string, bool) -> string;
    get-update-time(suuid) => { return "2023-09-14 19:11"; }
}

