export enum TabIndex {
    Rss,
    Add,
    Setting,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    language: string,
}

export struct SettingProxy {
    enabled: bool,
    url: string,
    port: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
    proxy: SettingProxy,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    out property<TabIndex> current-tab-index: TabIndex.Setting;

    in-out property<MessageItem> message;
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;
    in-out property<bool> is-cn:  setting-dialog-config.ui.language == "cn";

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "16",
            font-family: "SourceHanSerifCN",
            language: "cn",
        },
        proxy: {
            enabled: false,
            url: "127.0.0.1",
            port: "1080",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "rssbox v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/bitbox目录下。\n"
            + "  2. 数据保存在~/.local/share/bitbox目录下。\n"
            + "\n注意事项:\n"
            + "  1. 使用 blockstream API 进行交易广播，获取UTXO等链上信息。\n",

        text-en:
              "Configuration and data:\n"
            + "  1. Configuration is stored in the ~/.config/bitbox directory.\n"
            + "  2. Data is stored in the ~/.local/share/bitbox directory.\n"
            + "\nNote:\n"
            + "  1. Use blockstream API to broadcast transation, fetch UTXO and other on chain information.\n",
    };


    public function switch-tab(tab-index: TabIndex) {
        current-tab-index = tab-index;
    }
}


