import { Store } from "./store.slint";
import "./fonts/SourceHanSerifCN.ttf";

export global Theme  {
    out property<length> padding: 4px;
    out property<length> spacing: 4px;
    out property<length> header-height: 35px;
    out property<length> footer-height: 40px;
    out property<length> border-radius: 4px;
    out property<length> scroll-width: 12px;
    out property<length> dialog-max-width: 600px;

    in-out property<length> default-width: 550px;
    in-out property<length> default-height: 600px;
    in-out property<length> default-font-size: Store.setting-dialog-config.ui.font-size.to-float() * 1px;
    in-out property<length> enlarge-font-size: default-font-size + 1px;
    in-out property<length> body-font-size: default-font-size + 2px;
    in-out property<length> title5-font-size: default-font-size + 1px;
    in-out property<length> title4-font-size: default-font-size + 2px;
    in-out property<length> title3-font-size: default-font-size + 4px;
    in-out property<length> title2-font-size: default-font-size + 6px;
    in-out property<length> title1-font-size: default-font-size + 8px;

    in-out property<string> default-font-family: Store.setting-dialog-config.ui.font-family;

    out property<length> icon-size: 24px;
    out property<length> avatar-size: 32px;
    out property<length> default-label-width: 150px;
    out property<duration> default-animate-duration: 200ms;

    out property<color> brand-color: #0000B8;
    out property<color> success-color: #67C23A;
    out property<color> warning-color: #E6A23C;
    out property<color> danger-color: #F56C6C;
    out property<color> info-color: #909399;
    out property<color> discovery-color: #6E5DC6;
    out property<color> mark-color: Theme.warning-color;
    out property<color> unmark-color: Theme.dark-fill-color;

    out property<color> basic-black-color: #000000;
    out property<color> basic-white-color: #FFFFFF;
    out property<color> base-background-light: #FFFFFF;
    out property<color> base-background-dark: #1D232A;

    out property<color> pressed-color: Colors.lightgray;
    out property<color> pressed-color-dark: pressed-color.darker(15%);

    out property<color> primary-text-color: #202123;
    out property<color> regular-text-color: primary-text-color.brighter(50%);
    out property<color> secondary-text-color: primary-text-color.brighter(100%);
    out property<color> placeholder-text-color: #A8ABB2;
    out property<color> disabled-text-color: #C0C4CC;

    out property<color> icon-color: #515151;
    out property<color> brand-border-color: #005FB8;
    out property<color> base-border-color: #DCDFE6;
    out property<color> darker-border-color: #CDD0D6;
    out property<color> dark-border-color: #D4D7DE;
    out property<color> light-border-color: #E4E7ED;
    out property<color> lighter-border-color: #EBEEF5;

    out property<color> base-fill-color: #E8F2FD;
    out property<color> dark-fill-color: base-fill-color.darker(5%);
    out property<color> darker-fill-color: dark-fill-color.darker(5%);
    out property<color> light-fill-color: base-fill-color.brighter(5%);
    out property<color> lighter-fill-color: light-fill-color.brighter(10%);

    out property<color> have-read-text-color: #606060;
    out property<color> link-text-color: #0000B8;
    out property<color> avatar-color: primary-text-color.brighter(50%);

    out property<[color]> tag-colors: [#CCE0FF, #BAF3DB, #C1F0F5, #DFD8FD, #FFD2CC, #FDD0EC, #D3F1A7, #DCDFE4];
}

export global Icons  {
    out property<image> rss-fill: @image-url("./images/rss-fill.svg");
    out property<image> setting-fill: @image-url("./images/setting-fill.svg");
    out property<image> add-fill: @image-url("./images/add-fill.svg");
    out property<image> back: @image-url("./images/back.svg");
    out property<image> list: @image-url("./images/list.svg");
    out property<image> star: @image-url("./images/star.svg");
    out property<image> no-message: @image-url("./images/no-message.svg");
    out property<image> delete: @image-url("./images/delete-light.svg");
    out property<image> refresh: @image-url("./images/refresh.svg");
    out property<image> cancel-fill: @image-url("./images/cancel.svg");
    out property<image> cancel: @image-url("./images/cancel-light.svg");
    out property<image> success-fill: @image-url("./images/success-fill.svg");
    out property<image> close: @image-url("./images/close.svg");
}
