import { Theme } from "./theme.slint";

export global Util {
    callback string-fixed2(string) -> string;
    callback float-fixed2(float) -> string;
    callback open-url(string);

    pure callback text-len(string) -> int; // text
    pure callback rand-int(int, int) -> int; // low-bound, up-bound

    pure callback local-now(string) -> string;
    local-now => { return "12:34:45"; }

    pure callback format_number_with_commas(string) -> string;
    format_number-with-commas(number-str) => { return number-str; }

    pure callback split-and-join-string(string, int, string) -> string;
    split-and-join-string(input, length, sep) => { return input; }

    public pure function text-color(type: string) -> color {
       if (type == "success") {
           return Theme.success-color;
       } else if (type == "warning") {
           return Theme.warning-color.darker(10%);
       } else if (type == "danger") {
            return Theme.danger-color;
       }
       return Theme.info-color;
    }

    public pure function icon-source(type: string) -> image {
       if (type == "success") {
           return @image-url("./images/success.svg");
       } else if (type == "warning") {
           return @image-url("./images/warning.svg");
       } else if (type == "danger") {
           return @image-url("./images/danger.svg");
       }
       return @image-url("./images/info.svg");
    }
}
